import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:8765/',url=new URL('chunks.html',base).href;
const bank=JSON.parse(await readFile(new URL('../chunks-example.json',import.meta.url),'utf8'));
const flat=bank.sentences.flatMap(s=>s.chunks),out=new URL('../.qa/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Taipei',acceptDownloads:true}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const sentinel={'ielts100.bank.v1':'whole sentence bank unchanged','ielts100.progress.v1':'whole sentence progress unchanged','ielts100.narration.v1':'on','ielts100.feedback.v1':'on'};
await page.addInitScript(values=>{for(const [key,value] of Object.entries(values))if(!localStorage.getItem(key))localStorage.setItem(key,value);},sentinel);
const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ielts100.chunks.progress.v1')));
const focused=()=>page.evaluate(()=>document.activeElement?.id);
async function ready(){await page.waitForFunction(()=>document.getElementById('chunk-total').textContent.includes('项词伙'));}
async function write(answer){assert.equal(await focused(),'chunk-answer');await page.locator('#chunk-answer').fill(answer);await page.keyboard.press('Enter');await page.locator('#chunk-feedback').waitFor({state:'visible'});}
const parentUnchanged=async()=>assert.deepEqual(await page.evaluate(keys=>Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)])),Object.keys(sentinel)),sentinel);
async function importBank(value){await page.locator('#chunk-settings-open').click();page.once('dialog',d=>d.accept());await page.locator('#chunk-import').setInputFiles({name:'chunks.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await page.waitForFunction(()=>!document.getElementById('chunk-settings-message').hidden);assert.ok(!(await page.locator('#chunk-settings-message').getAttribute('class')).includes('error'));await page.keyboard.press('Escape');}
try{
  await page.goto(url);await ready();assert.equal(await page.locator('#chunk-total').textContent(),'6 句 · 12 项词伙');assert.equal(await page.locator('#browse-source').textContent(),bank.sentences[0].english);assert.equal(await page.locator('#chunk-cards .chunk-item').count(),2);assert.ok(await page.locator('.grammar-mark').count()>0);
  await page.screenshot({path:fileURLToPath(new URL('chunks-browse-demo.png',out)),fullPage:true});
  await page.locator('body').click({position:{x:5,y:150}});await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#browse-number').textContent(),'02 / 6');await page.reload();await ready();assert.equal(await page.locator('#browse-number').textContent(),'02 / 6');await page.keyboard.press('ArrowLeft');
  await page.locator('#drill-mode').click();assert.equal(await focused(),'chunk-answer');assert.equal(await page.locator('#chunk-meaning').textContent(),'散步');assert.equal(await page.locator('#chunk-feedback').isVisible(),false);assert.equal(await page.locator('#browse-panel').isVisible(),false);assert.ok(!(await page.locator('body').innerText()).includes('take a walk'));
  await page.keyboard.press('Enter');assert.equal((await state()).log.length,0);
  await write('take walk');assert.equal(await focused(),'chunk-retry');assert.equal(await page.locator('#chunk-next').isVisible(),false);assert.equal((await state()).log.length,1);assert.equal(await page.locator('#chunk-wrong').textContent(),'1');
  await page.reload();await page.locator('#chunk-feedback').waitFor({state:'visible'});assert.equal(await focused(),'chunk-retry');await page.keyboard.press('Enter');assert.equal(await focused(),'chunk-answer');await page.locator('#chunk-records').evaluate(e=>e.open=true);assert.ok(!(await page.locator('body').innerText()).includes('take a walk'));assert.equal(await page.locator('#drill-notes').textContent(),'');
  await page.locator('#chunk-answer').fill('TAKE');await page.reload();await page.waitForFunction(()=>document.activeElement?.id==='chunk-answer');assert.equal(await page.locator('#chunk-answer').inputValue(),'TAKE');await write('TAKE A WALK!!!');assert.equal((await state()).log[1].repair,true);assert.equal(await focused(),'chunk-next');assert.equal(await page.locator('#chunk-correct').textContent(),'1');await page.keyboard.press('Enter');assert.equal((await state()).active.id,flat[1].id);
  for(const c of flat.slice(1)){await write(c.english);await page.keyboard.press('Enter');}
  assert.equal(await page.locator('#chunk-complete').isVisible(),true);assert.equal(await focused(),'round-all');assert.equal((await state()).log.length,13);await page.reload();await page.locator('#chunk-complete').waitFor({state:'visible'});assert.equal(await focused(),'round-all');
  await page.locator('#chunk-records').evaluate(e=>e.open=true);await page.locator('#chunk-log-filter').selectOption('wrong');assert.equal(await page.locator('.journal-item').count(),1);await page.locator('#chunk-log-filter').selectOption('correct');assert.equal(await page.locator('.journal-item').count(),12);
  const downloadEvent=page.waitForEvent('download');await page.locator('#chunk-export').click();const download=await downloadEvent,backup=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(backup.format,'ielts100-chunks-backup');assert.equal(backup.progress.log.length,13);
  await page.locator('#round-errors').click();assert.equal((await state()).queue.length,1);assert.ok(!(await page.locator('body').innerText()).includes('take a walk'));await write(flat[0].english);await page.keyboard.press('Enter');assert.equal(await page.locator('#chunk-complete').isVisible(),true);
  await parentUnchanged();await page.locator('#chunk-settings-open').click();const before=await state();await page.locator('#chunk-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({sentences:[]}))});await page.waitForFunction(()=>document.getElementById('chunk-settings-message').classList.contains('error'));assert.deepEqual(await state(),before);
  page.once('dialog',d=>d.accept());await page.locator('#chunk-reset').click();assert.equal((await state()).log.length,0);await page.keyboard.press('Escape');await parentUnchanged();await importBank(backup);assert.equal((await state()).log.length,13);assert.equal(await page.locator('#chunk-complete').isVisible(),true);
  // Imported study data must never become executable HTML.
  const evil=structuredClone(bank);evil.title='Text-only import';evil.sentences[0].chunks[0].meaning='<img src=x onerror="window.hacked=true">';await importBank(evil);await page.locator('#browse-mode').click();await page.locator('#sentence-jump').selectOption('0');assert.equal(await page.locator('#chunk-cards img').count(),0);assert.equal(await page.evaluate(()=>window.hacked),undefined);
  // Optional private bank stays in this isolated browser; it is not a shipped fixture.
  if(process.env.CHUNKS_FILE){const formal=JSON.parse(await readFile(process.env.CHUNKS_FILE,'utf8'));await importBank(formal);await page.locator('#browse-mode').click();await page.locator('#sentence-jump').selectOption('0');assert.equal(await page.locator('#chunk-total').textContent(),'100 句 · 273 项词伙');assert.equal(await page.locator('#browse-source').textContent(),formal.sentences[0].english);
    await page.locator('#chunk-records').evaluate(e=>e.open=false);await page.locator('#theme-toggle').click();await page.screenshot({path:fileURLToPath(new URL('chunks-100-browse.png',out)),fullPage:true});
    await page.locator('#drill-mode').click();await write('exercise');await page.screenshot({path:fileURLToPath(new URL('chunks-100-diff.png',out)),fullPage:true});await page.keyboard.press('Enter');await write(formal.sentences[0].chunks[0].english);await page.keyboard.press('Enter');
    const phrases=formal.sentences.flatMap(s=>s.chunks);for(const c of phrases.slice(1)){await write(c.english);await page.keyboard.press('Enter');}assert.equal(await page.locator('#chunk-complete').isVisible(),true);assert.equal((await state()).log.length,274);assert.equal((await state()).log.filter(e=>e.correct).length,273);await parentUnchanged();
    await page.locator('#browse-mode').click();await page.locator('#sentence-jump').selectOption('2');assert.match(await page.locator('#browse-source-notes').textContent(),/teachers/);assert.equal(await page.locator('#browse-source').textContent(),formal.sentences[2].english);
  }
  await page.locator('#browse-mode').click();await page.locator('#sentence-jump').selectOption('0');await page.locator('#chunk-records').evaluate(e=>e.open=false);
  for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`browse width ${width}`);await page.locator('#theme-toggle').click();await page.screenshot({path:fileURLToPath(new URL(`chunks-mobile-${width}.png`,out)),fullPage:true});await page.locator('#drill-mode').click();if(await page.locator('#round-all').isVisible())await page.locator('#round-all').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`drill width ${width}`);await page.locator('#browse-mode').click();}
  assert.deepEqual(errors,[]);console.log('Chunks browser: browse order, no hints, keyboard round, correction, reload, separate records, backup, injection safety, full private bank, desktop/mobile passed.');
}finally{await browser.close();}
